[package]
name = "diesel_bookstore_assessment"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.4", features = ["postgres"] }
dotenvy = "0.15.7"
eyre = "0.6.12"
rand = "0.8.5"

[dev-dependencies]
assert_cmd = "2.0.16"
